"""create resumes table"""

from alembic import op
import sqlalchemy as sa


# ================================================================
# REVISION IDENTIFIERS
# ================================================================

revision = "003_resumes"
down_revision = "002_jobs"
branch_labels = None
depends_on = None


# ================================================================
# UPGRADE
# ================================================================

def upgrade() -> None:
    """Create the resumes table."""

    op.create_table(
        "resumes",

        # Primary key
        sa.Column(
            "id",
            sa.Integer(),
            primary_key=True,
            autoincrement=True,
        ),

        # User / recruiter who uploaded the resume
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),

        # Candidate reference.
        # Nullable because a resume can be uploaded
        # before the candidate is created.
        sa.Column(
            "candidate_id",
            sa.Integer(),
            nullable=True,
        ),

        # Resume file information
        sa.Column(
            "file_name",
            sa.String(255),
            nullable=False,
        ),

        sa.Column(
            "file_path",
            sa.String(500),
            nullable=True,
        ),

        sa.Column(
            "file_type",
            sa.String(50),
            nullable=True,
        ),

        # Extracted resume text
        sa.Column(
            "raw_text",
            sa.Text(),
            nullable=True,
        ),

        # AI parsed resume information
        sa.Column(
            "parsed_data",
            sa.JSON(),
            nullable=True,
        ),

        # ATS score generated by AI
        sa.Column(
            "ats_score",
            sa.Float(),
            nullable=True,
        ),

        # uploaded / processing / analyzed / failed
        sa.Column(
            "status",
            sa.String(50),
            nullable=False,
            server_default="uploaded",
        ),

        # Timestamps
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),

        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),

        # User relationship
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_resumes_user_id_users",
            ondelete="CASCADE",
        ),
    )

    # ============================================================
    # INDEXES
    # ============================================================

    op.create_index(
        "ix_resumes_user_id",
        "resumes",
        ["user_id"],
    )

    op.create_index(
        "ix_resumes_candidate_id",
        "resumes",
        ["candidate_id"],
    )

    op.create_index(
        "ix_resumes_ats_score",
        "resumes",
        ["ats_score"],
    )

    op.create_index(
        "ix_resumes_status",
        "resumes",
        ["status"],
    )


# ================================================================
# DOWNGRADE
# ================================================================

def downgrade() -> None:
    """Drop the resumes table."""

    op.drop_index(
        "ix_resumes_status",
        table_name="resumes",
    )

    op.drop_index(
        "ix_resumes_ats_score",
        table_name="resumes",
    )

    op.drop_index(
        "ix_resumes_candidate_id",
        table_name="resumes",
    )

    op.drop_index(
        "ix_resumes_user_id",
        table_name="resumes",
    )

    op.drop_table("resumes")