# Project scaffold file
"""
genai/copilot/recommendations.py

Recruiter Copilot Recommendation Engine
========================================

Generates structured recommendations for recruiters.

Responsibilities:
- Candidate recommendations
- Resume improvement recommendations
- Interview recommendations
- Skill-gap recommendations
- Hiring pipeline recommendations
- Ranking explanations
- Recommendation prioritization
- Confidence estimation
- Human-review safeguards

This module does NOT make final hiring decisions.
It provides decision-support recommendations for a human recruiter.
"""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


logger = logging.getLogger(__name__)


# ============================================================================
# ENUMS
# ============================================================================


class RecommendationType(str, Enum):
    """
    Types of recommendations generated by the Copilot.
    """

    SHORTLIST = "shortlist"
    REVIEW = "review"
    REJECT_REVIEW = "reject_review"
    INTERVIEW = "interview"
    RESUME_IMPROVEMENT = "resume_improvement"
    SKILL_GAP = "skill_gap"
    CANDIDATE_COMPARISON = "candidate_comparison"
    PIPELINE = "pipeline"
    INTERVIEW_FEEDBACK = "interview_feedback"
    GENERAL = "general"


class RecommendationPriority(str, Enum):
    """
    Recommendation priority.
    """

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


# ============================================================================
# DATA MODELS
# ============================================================================


@dataclass
class Recommendation:
    """
    A single recruiter recommendation.
    """

    type: RecommendationType

    title: str

    message: str

    priority: RecommendationPriority = (
        RecommendationPriority.MEDIUM
    )

    confidence: float = 0.0

    candidate_id: Optional[str] = None

    job_id: Optional[str] = None

    evidence: List[str] = field(
        default_factory=list
    )

    strengths: List[str] = field(
        default_factory=list
    )

    concerns: List[str] = field(
        default_factory=list
    )

    suggested_actions: List[str] = field(
        default_factory=list
    )

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )


@dataclass
class RecommendationResult:
    """
    Collection of recommendations.
    """

    recommendations: List[Recommendation] = field(
        default_factory=list
    )

    summary: str = ""

    overall_confidence: float = 0.0

    requires_human_review: bool = True

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================


def clamp(
    value: float,
    minimum: float = 0.0,
    maximum: float = 1.0,
) -> float:
    """
    Clamp a numeric value between minimum and maximum.
    """

    return max(
        minimum,
        min(maximum, value),
    )


def normalize_score(
    value: Any,
) -> Optional[float]:
    """
    Convert a score into a 0-1 range.

    Supports:
        0.85
        85
        "85"
    """

    if value is None:
        return None

    try:
        score = float(value)
    except (
        TypeError,
        ValueError,
    ):
        return None

    if score > 1:
        score /= 100

    return clamp(score)


def unique_strings(
    values: List[str],
) -> List[str]:
    """
    Remove duplicate strings while preserving order.
    """

    seen = set()
    result = []

    for value in values:

        if not value:
            continue

        normalized = str(value).strip()

        if not normalized:
            continue

        key = normalized.lower()

        if key in seen:
            continue

        seen.add(key)
        result.append(normalized)

    return result


def priority_from_score(
    score: Optional[float],
) -> RecommendationPriority:
    """
    Convert a normalized score into recommendation priority.
    """

    if score is None:
        return RecommendationPriority.MEDIUM

    if score >= 0.85:
        return RecommendationPriority.HIGH

    if score >= 0.65:
        return RecommendationPriority.MEDIUM

    return RecommendationPriority.LOW


# ============================================================================
# RECOMMENDATION ENGINE
# ============================================================================


class RecommendationEngine:
    """
    Main recommendation engine for Recruiter Copilot.
    """

    def __init__(
        self,
        shortlist_threshold: float = 0.75,
        interview_threshold: float = 0.70,
        review_threshold: float = 0.50,
    ) -> None:

        self.shortlist_threshold = (
            shortlist_threshold
        )

        self.interview_threshold = (
            interview_threshold
        )

        self.review_threshold = (
            review_threshold
        )

    # ------------------------------------------------------------------------
    # CANDIDATE RECOMMENDATION
    # ------------------------------------------------------------------------

    def recommend_candidate(
        self,
        candidate: Dict[str, Any],
        job: Optional[Dict[str, Any]] = None,
    ) -> Recommendation:

        candidate_id = candidate.get(
            "candidate_id",
            candidate.get("id"),
        )

        job_id = (
            job.get(
                "job_id",
                job.get("id"),
            )
            if job
            else None
        )

        score = self._candidate_score(
            candidate
        )

        strengths = self._extract_strengths(
            candidate
        )

        concerns = self._extract_concerns(
            candidate
        )

        evidence = self._build_candidate_evidence(
            candidate
        )

        if score is None:

            return Recommendation(
                type=RecommendationType.REVIEW,
                title="Manual Candidate Review",
                message=(
                    "There is not enough scoring data "
                    "to make a reliable recommendation."
                ),
                priority=RecommendationPriority.MEDIUM,
                confidence=0.30,
                candidate_id=candidate_id,
                job_id=job_id,
                evidence=evidence,
                strengths=strengths,
                concerns=concerns,
                suggested_actions=[
                    "Review the candidate profile manually.",
                    "Complete resume and interview evaluation "
                    "before making a decision.",
                ],
            )

        if score >= self.shortlist_threshold:

            return Recommendation(
                type=RecommendationType.SHORTLIST,
                title="Strong Candidate",
                message=(
                    "The candidate appears well aligned "
                    "with the available evaluation signals "
                    "and may be suitable for shortlisting."
                ),
                priority=RecommendationPriority.HIGH,
                confidence=clamp(score),
                candidate_id=candidate_id,
                job_id=job_id,
                evidence=evidence,
                strengths=strengths,
                concerns=concerns,
                suggested_actions=[
                    "Review the candidate profile.",
                    "Verify key qualifications.",
                    "Consider advancing to the next stage.",
                ],
            )

        if score >= self.interview_threshold:

            return Recommendation(
                type=RecommendationType.INTERVIEW,
                title="Consider for Interview",
                message=(
                    "The candidate shows promising signals "
                    "but additional human evaluation is recommended."
                ),
                priority=RecommendationPriority.MEDIUM,
                confidence=clamp(score),
                candidate_id=candidate_id,
                job_id=job_id,
                evidence=evidence,
                strengths=strengths,
                concerns=concerns,
                suggested_actions=[
                    "Conduct a structured interview.",
                    "Validate technical skills.",
                    "Review identified skill gaps.",
                ],
            )

        if score >= self.review_threshold:

            return Recommendation(
                type=RecommendationType.REVIEW,
                title="Requires Further Review",
                message=(
                    "The candidate has mixed evaluation signals. "
                    "Additional review is recommended before advancing."
                ),
                priority=RecommendationPriority.MEDIUM,
                confidence=clamp(score),
                candidate_id=candidate_id,
                job_id=job_id,
                evidence=evidence,
                strengths=strengths,
                concerns=concerns,
                suggested_actions=[
                    "Review resume evidence.",
                    "Compare skills against job requirements.",
                    "Consider a structured screening interview.",
                ],
            )

        return Recommendation(
            type=RecommendationType.REVIEW,
            title="Low Match Signal",
            message=(
                "Available evaluation signals indicate "
                "a relatively weak match. Human review is "
                "recommended before taking action."
            ),
            priority=RecommendationPriority.LOW,
            confidence=clamp(
                1 - score
            ),
            candidate_id=candidate_id,
            job_id=job_id,
            evidence=evidence,
            strengths=strengths,
            concerns=concerns,
            suggested_actions=[
                "Review the candidate manually.",
                "Check whether missing skills are actually required.",
            ],
        )

    # ------------------------------------------------------------------------
    # CANDIDATE SCORE
    # ------------------------------------------------------------------------

    def _candidate_score(
        self,
        candidate: Dict[str, Any],
    ) -> Optional[float]:

        scores = candidate.get(
            "scores",
            {},
        )

        if not isinstance(
            scores,
            dict,
        ):
            scores = {}

        score_keys = [
            "overall",
            "overall_score",
            "match_score",
            "ats_score",
            "technical_score",
        ]

        for key in score_keys:

            score = normalize_score(
                scores.get(key)
            )

            if score is not None:
                return score

        for key in [
            "score",
            "overall_score",
            "match_score",
        ]:

            score = normalize_score(
                candidate.get(key)
            )

            if score is not None:
                return score

        return None

    # ------------------------------------------------------------------------
    # STRENGTHS
    # ------------------------------------------------------------------------

    def _extract_strengths(
        self,
        candidate: Dict[str, Any],
    ) -> List[str]:

        strengths = []

        skills = candidate.get(
            "skills",
            [],
        )

        if skills:

            strengths.append(
                "Relevant skills detected: "
                + ", ".join(
                    str(skill)
                    for skill in skills[:8]
                )
            )

        scores = candidate.get(
            "scores",
            {},
        )

        if isinstance(
            scores,
            dict,
        ):

            for key, label in [
                (
                    "technical_score",
                    "technical evaluation",
                ),
                (
                    "communication_score",
                    "communication evaluation",
                ),
                (
                    "experience_score",
                    "experience evaluation",
                ),
                (
                    "education_score",
                    "education evaluation",
                ),
            ]:

                score = normalize_score(
                    scores.get(key)
                )

                if (
                    score is not None
                    and score >= 0.75
                ):

                    strengths.append(
                        f"Strong {label} signal."
                    )

        return unique_strings(
            strengths
        )

    # ------------------------------------------------------------------------
    # CONCERNS
    # ------------------------------------------------------------------------

    def _extract_concerns(
        self,
        candidate: Dict[str, Any],
    ) -> List[str]:

        concerns = []

        skill_gaps = candidate.get(
            "skill_gaps",
            [],
        )

        if skill_gaps:

            concerns.append(
                "Potential skill gaps: "
                + ", ".join(
                    str(skill)
                    for skill in skill_gaps[:8]
                )
            )

        scores = candidate.get(
            "scores",
            {},
        )

        if isinstance(
            scores,
            dict,
        ):

            for key, label in [
                (
                    "technical_score",
                    "technical evaluation",
                ),
                (
                    "communication_score",
                    "communication evaluation",
                ),
                (
                    "experience_score",
                    "experience evaluation",
                ),
            ]:

                score = normalize_score(
                    scores.get(key)
                )

                if (
                    score is not None
                    and score < 0.50
                ):

                    concerns.append(
                        f"Low {label} signal."
                    )

        return unique_strings(
            concerns
        )

    # ------------------------------------------------------------------------
    # EVIDENCE
    # ------------------------------------------------------------------------

    def _build_candidate_evidence(
        self,
        candidate: Dict[str, Any],
    ) -> List[str]:

        evidence = []

        score = self._candidate_score(
            candidate
        )

        if score is not None:

            evidence.append(
                f"Overall evaluation score: "
                f"{score * 100:.1f}%"
            )

        skills = candidate.get(
            "skills",
            [],
        )

        if skills:

            evidence.append(
                f"{len(skills)} candidate skill(s) "
                "were available for evaluation."
            )

        experience = candidate.get(
            "experience",
            [],
        )

        if experience:

            evidence.append(
                f"{len(experience)} experience "
                "record(s) were available."
            )

        return unique_strings(
            evidence
        )

    # ------------------------------------------------------------------------
    # SKILL GAP RECOMMENDATIONS
    # ------------------------------------------------------------------------

    def recommend_skill_gaps(
        self,
        candidate: Dict[str, Any],
        job: Dict[str, Any],
    ) -> List[Recommendation]:

        candidate_skills = {
            str(skill).lower()
            for skill in candidate.get(
                "skills",
                [],
            )
        }

        required_skills = job.get(
            "skills",
            job.get(
                "required_skills",
                [],
            ),
        )

        recommendations = []

        missing = []

        for skill in required_skills:

            normalized = str(
                skill
            ).lower()

            if normalized not in candidate_skills:

                missing.append(
                    str(skill)
                )

        if not missing:

            return [
                Recommendation(
                    type=RecommendationType.SKILL_GAP,
                    title="No Major Skill Gaps Detected",
                    message=(
                        "The candidate appears to cover "
                        "the listed job skills."
                    ),
                    priority=RecommendationPriority.LOW,
                    confidence=0.85,
                    candidate_id=candidate.get(
                        "candidate_id",
                        candidate.get("id"),
                    ),
                    job_id=job.get(
                        "job_id",
                        job.get("id"),
                    ),
                    evidence=[
                        "Required skills were compared "
                        "with candidate skills."
                    ],
                )
            ]

        return [
            Recommendation(
                type=RecommendationType.SKILL_GAP,
                title="Skill Gaps Identified",
                message=(
                    "Some listed job requirements were "
                    "not found in the available candidate profile."
                ),
                priority=RecommendationPriority.MEDIUM,
                confidence=0.75,
                candidate_id=candidate.get(
                    "candidate_id",
                    candidate.get("id"),
                ),
                job_id=job.get(
                    "job_id",
                    job.get("id"),
                ),
                evidence=[
                    "Job requirements were compared "
                    "against candidate skills."
                ],
                concerns=[
                    f"Missing or unverified skill: {skill}"
                    for skill in missing
                ],
                suggested_actions=[
                    "Verify whether each skill is actually "
                    "required for the role.",
                    "Ask structured interview questions "
                    "about missing skills.",
                    "Check project and experience evidence "
                    "before treating a skill as missing.",
                ],
                metadata={
                    "missing_skills": missing
                },
            )
        ]

    # ------------------------------------------------------------------------
    # RESUME RECOMMENDATIONS
    # ------------------------------------------------------------------------

    def recommend_resume_improvements(
        self,
        resume: Dict[str, Any],
        job: Optional[Dict[str, Any]] = None,
    ) -> List[Recommendation]:

        recommendations = []

        skills = resume.get(
            "skills",
            [],
        )

        summary = resume.get(
            "summary"
        )

        experience = resume.get(
            "experience",
            [],
        )

        ats_score = normalize_score(
            resume.get(
                "ats_score"
            )
        )

        if not summary:

            recommendations.append(
                Recommendation(
                    type=RecommendationType.RESUME_IMPROVEMENT,
                    title="Improve Resume Summary",
                    message=(
                        "Add a concise professional summary "
                        "that highlights role-relevant experience."
                    ),
                    priority=RecommendationPriority.MEDIUM,
                    confidence=0.90,
                    suggested_actions=[
                        "Add a 2-4 sentence professional summary.",
                        "Focus on measurable achievements.",
                        "Align wording with verified job requirements.",
                    ],
                )
            )

        if not skills:

            recommendations.append(
                Recommendation(
                    type=RecommendationType.RESUME_IMPROVEMENT,
                    title="Add a Skills Section",
                    message=(
                        "No structured skills were detected "
                        "in the available resume data."
                    ),
                    priority=RecommendationPriority.HIGH,
                    confidence=0.90,
                    suggested_actions=[
                        "Add a clearly labeled skills section.",
                        "Include relevant technical and professional skills.",
                    ],
                )
            )

        if not experience:

            recommendations.append(
                Recommendation(
                    type=RecommendationType.RESUME_IMPROVEMENT,
                    title="Add Experience Evidence",
                    message=(
                        "No structured experience records "
                        "were detected."
                    ),
                    priority=RecommendationPriority.HIGH,
                    confidence=0.90,
                    suggested_actions=[
                        "Add relevant employment or project experience.",
                        "Use measurable outcomes where available.",
                    ],
                )
            )

        if (
            ats_score is not None
            and ats_score < 0.70
        ):

            recommendations.append(
                Recommendation(
                    type=RecommendationType.RESUME_IMPROVEMENT,
                    title="Improve ATS Compatibility",
                    message=(
                        "The available ATS score suggests "
                        "the resume could be improved for machine-readable "
                        "formatting and job relevance."
                    ),
                    priority=RecommendationPriority.HIGH,
                    confidence=0.85,
                    evidence=[
                        f"ATS score: {ats_score * 100:.1f}%"
                    ],
                    suggested_actions=[
                        "Use standard section headings.",
                        "Improve alignment with verified job requirements.",
                        "Avoid unnecessary formatting complexity.",
                    ],
                )
            )

        if job:

            job_skills = {
                str(skill).lower()
                for skill in job.get(
                    "skills",
                    [],
                )
            }

            resume_skills = {
                str(skill).lower()
                for skill in skills
            }

            missing = (
                job_skills
                - resume_skills
            )

            if missing:

                recommendations.append(
                    Recommendation(
                        type=RecommendationType.RESUME_IMPROVEMENT,
                        title="Improve Job Alignment",
                        message=(
                            "Some job skills were not detected "
                            "in the structured resume information."
                        ),
                        priority=RecommendationPriority.MEDIUM,
                        confidence=0.75,
                        concerns=[
                            f"Unverified resume skill: {skill}"
                            for skill in sorted(
                                missing
                            )
                        ],
                        suggested_actions=[
                            "Add relevant skills only when "
                            "they are genuinely supported by experience.",
                            "Highlight relevant projects or achievements.",
                        ],
                    )
                )

        return recommendations

    # ------------------------------------------------------------------------
    # INTERVIEW RECOMMENDATIONS
    # ------------------------------------------------------------------------

    def recommend_interview(
        self,
        candidate: Dict[str, Any],
        job: Dict[str, Any],
    ) -> Recommendation:

        skill_gaps = candidate.get(
            "skill_gaps",
            [],
        )

        questions = []

        for skill in skill_gaps[:5]:

            questions.append(
                f"Verify the candidate's practical "
                f"experience with {skill}."
            )

        questions.extend(
            [
                "Ask for a specific example demonstrating "
                "a relevant achievement.",
                "Use the same core evaluation criteria "
                "for comparable candidates.",
            ]
        )

        return Recommendation(
            type=RecommendationType.INTERVIEW,
            title="Structured Interview Recommended",
            message=(
                "A structured interview can help validate "
                "the candidate's relevant skills and experience."
            ),
            priority=RecommendationPriority.MEDIUM,
            confidence=0.80,
            candidate_id=candidate.get(
                "candidate_id",
                candidate.get("id"),
            ),
            job_id=job.get(
                "job_id",
                job.get("id"),
            ),
            suggested_actions=questions,
            metadata={
                "focus_areas": skill_gaps[:5]
            },
        )

    # ------------------------------------------------------------------------
    # INTERVIEW FEEDBACK
    # ------------------------------------------------------------------------

    def recommend_from_interview(
        self,
        interview: Dict[str, Any],
    ) -> List[Recommendation]:

        recommendations = []

        scores = interview.get(
            "scores",
            {},
        )

        if not isinstance(
            scores,
            dict,
        ):
            scores = {}

        for key, label in [
            (
                "technical_score",
                "technical skills",
            ),
            (
                "communication_score",
                "communication",
            ),
            (
                "confidence_score",
                "confidence",
            ),
        ]:

            score = normalize_score(
                scores.get(key)
            )

            if score is None:
                continue

            if score < 0.50:

                recommendations.append(
                    Recommendation(
                        type=RecommendationType.INTERVIEW_FEEDBACK,
                        title=f"Review {label.title()}",
                        message=(
                            f"The interview evaluation "
                            f"shows a relatively low signal "
                            f"for {label}."
                        ),
                        priority=RecommendationPriority.MEDIUM,
                        confidence=0.75,
                        evidence=[
                            f"{label.title()} score: "
                            f"{score * 100:.1f}%"
                        ],
                        suggested_actions=[
                            f"Review the interview evidence "
                            f"supporting the {label} score.",
                            "Consider a follow-up structured "
                            "assessment if appropriate.",
                        ],
                    )
                )

        if not recommendations:

            recommendations.append(
                Recommendation(
                    type=RecommendationType.INTERVIEW_FEEDBACK,
                    title="Interview Signals Are Positive",
                    message=(
                        "The available interview evaluation "
                        "does not show a major low-scoring area."
                    ),
                    priority=RecommendationPriority.LOW,
                    confidence=0.70,
                    suggested_actions=[
                        "Review the full interview evidence.",
                        "Compare against the predefined job criteria.",
                    ],
                )
            )

        return recommendations

    # ------------------------------------------------------------------------
    # COMPARE CANDIDATES
    # ------------------------------------------------------------------------

    def compare_candidates(
        self,
        candidates: List[Dict[str, Any]],
        job: Optional[Dict[str, Any]] = None,
    ) -> RecommendationResult:

        scored = []

        for candidate in candidates:

            score = self._candidate_score(
                candidate
            )

            scored.append(
                (
                    candidate,
                    score,
                )
            )

        scored.sort(
            key=lambda item: (
                item[1]
                if item[1] is not None
                else -1
            ),
            reverse=True,
        )

        recommendations = []

        for index, (
            candidate,
            score,
        ) in enumerate(
            scored
        ):

            candidate_id = candidate.get(
                "candidate_id",
                candidate.get("id"),
            )

            if index == 0:

                title = (
                    "Highest Available Match Signal"
                )

                priority = (
                    RecommendationPriority.HIGH
                )

            else:

                title = (
                    "Candidate Comparison Result"
                )

                priority = (
                    RecommendationPriority.MEDIUM
                )

            confidence = (
                clamp(score)
                if score is not None
                else 0.30
            )

            recommendations.append(
                Recommendation(
                    type=RecommendationType.CANDIDATE_COMPARISON,
                    title=title,
                    message=(
                        "This candidate has the "
                        "highest available evaluation "
                        "signal among the supplied candidates."
                        if index == 0
                        else
                        "This candidate should be compared "
                        "against the role criteria and other "
                        "candidates using the same evaluation framework."
                    ),
                    priority=priority,
                    confidence=confidence,
                    candidate_id=candidate_id,
                    job_id=(
                        job.get(
                            "job_id",
                            job.get("id"),
                        )
                        if job
                        else None
                    ),
                    evidence=(
                        [
                            f"Evaluation score: "
                            f"{score * 100:.1f}%"
                        ]
                        if score is not None
                        else [
                            "No normalized evaluation score available."
                        ]
                    ),
                )
            )

        return RecommendationResult(
            recommendations=recommendations,
            summary=(
                "Candidates were ordered using the "
                "available evaluation signals. "
                "This ranking is decision support and "
                "requires human review."
            ),
            overall_confidence=(
                self._average_confidence(
                    recommendations
                )
            ),
            requires_human_review=True,
            metadata={
                "candidate_count": len(
                    candidates
                )
            },
        )

    # ------------------------------------------------------------------------
    # PIPELINE RECOMMENDATIONS
    # ------------------------------------------------------------------------

    def recommend_pipeline(
        self,
        analytics: Dict[str, Any],
    ) -> List[Recommendation]:

        recommendations = []

        funnel = analytics.get(
            "funnel",
            {},
        )

        if not isinstance(
            funnel,
            dict,
        ):
            funnel = {}

        application_count = self._number(
            funnel.get(
                "applications"
            )
        )

        interview_count = self._number(
            funnel.get(
                "interviews"
            )
        )

        hired_count = self._number(
            funnel.get(
                "hires"
            )
        )

        if (
            application_count
            and interview_count is not None
        ):

            interview_rate = (
                interview_count
                / application_count
            )

            if interview_rate < 0.10:

                recommendations.append(
                    Recommendation(
                        type=RecommendationType.PIPELINE,
                        title="Low Interview Conversion",
                        message=(
                            "The available funnel data shows "
                            "a relatively low application-to-interview "
                            "conversion rate."
                        ),
                        priority=RecommendationPriority.HIGH,
                        confidence=0.80,
                        evidence=[
                            f"Interview conversion: "
                            f"{interview_rate * 100:.1f}%"
                        ],
                        suggested_actions=[
                            "Review screening criteria.",
                            "Check whether qualified applicants "
                            "are being filtered out too early.",
                            "Audit the screening workflow.",
                        ],
                    )
                )

        if (
            interview_count
            and hired_count is not None
        ):

            hire_rate = (
                hired_count
                / interview_count
            )

            if hire_rate < 0.10:

                recommendations.append(
                    Recommendation(
                        type=RecommendationType.PIPELINE,
                        title="Low Interview-to-Hire Conversion",
                        message=(
                            "The available funnel data suggests "
                            "that relatively few interviewed candidates "
                            "are progressing to hire."
                        ),
                        priority=RecommendationPriority.MEDIUM,
                        confidence=0.75,
                        evidence=[
                            f"Interview-to-hire conversion: "
                            f"{hire_rate * 100:.1f}%"
                        ],
                        suggested_actions=[
                            "Review interview criteria.",
                            "Check consistency of interviewer scoring.",
                            "Compare rejection reasons.",
                        ],
                    )
                )

        if not recommendations:

            recommendations.append(
                Recommendation(
                    type=RecommendationType.PIPELINE,
                    title="Review Recruitment Funnel",
                    message=(
                        "Continue monitoring funnel metrics "
                        "to identify meaningful changes in conversion."
                    ),
                    priority=RecommendationPriority.LOW,
                    confidence=0.60,
                    suggested_actions=[
                        "Monitor application volume.",
                        "Monitor interview conversion.",
                        "Monitor time-to-hire.",
                    ],
                )
            )

        return recommendations

    # ------------------------------------------------------------------------
    # GENERAL RECOMMENDATIONS
    # ------------------------------------------------------------------------

    def generate(
        self,
        *,
        candidate: Optional[
            Dict[str, Any]
        ] = None,
        job: Optional[
            Dict[str, Any]
        ] = None,
        resume: Optional[
            Dict[str, Any]
        ] = None,
        interview: Optional[
            Dict[str, Any]
        ] = None,
        analytics: Optional[
            Dict[str, Any]
        ] = None,
    ) -> RecommendationResult:

        recommendations: List[
            Recommendation
        ] = []

        if candidate:

            recommendations.append(
                self.recommend_candidate(
                    candidate,
                    job,
                )
            )

            if job:

                recommendations.extend(
                    self.recommend_skill_gaps(
                        candidate,
                        job,
                    )
                )

                recommendations.append(
                    self.recommend_interview(
                        candidate,
                        job,
                    )
                )

        if resume:

            recommendations.extend(
                self.recommend_resume_improvements(
                    resume,
                    job,
                )
            )

        if interview:

            recommendations.extend(
                self.recommend_from_interview(
                    interview
                )
            )

        if analytics:

            recommendations.extend(
                self.recommend_pipeline(
                    analytics
                )
            )

        recommendations = (
            self.prioritize(
                recommendations
            )
        )

        return RecommendationResult(
            recommendations=recommendations,
            summary=self._build_summary(
                recommendations
            ),
            overall_confidence=(
                self._average_confidence(
                    recommendations
                )
            ),
            requires_human_review=True,
            metadata={
                "recommendation_count": len(
                    recommendations
                )
            },
        )

    # ------------------------------------------------------------------------
    # PRIORITIZATION
    # ------------------------------------------------------------------------

    def prioritize(
        self,
        recommendations: List[Recommendation],
    ) -> List[Recommendation]:

        priority_order = {
            RecommendationPriority.CRITICAL: 0,
            RecommendationPriority.HIGH: 1,
            RecommendationPriority.MEDIUM: 2,
            RecommendationPriority.LOW: 3,
        }

        return sorted(
            recommendations,
            key=lambda item: (
                priority_order.get(
                    item.priority,
                    99,
                ),
                -item.confidence,
            ),
        )

    # ------------------------------------------------------------------------
    # SUMMARY
    # ------------------------------------------------------------------------

    def _build_summary(
        self,
        recommendations: List[Recommendation],
    ) -> str:

        if not recommendations:

            return (
                "No recommendations could be generated "
                "from the available information."
            )

        high_priority = sum(
            1
            for recommendation in recommendations
            if recommendation.priority
            in {
                RecommendationPriority.CRITICAL,
                RecommendationPriority.HIGH,
            }
        )

        return (
            f"{len(recommendations)} recommendation(s) "
            f"were generated. "
            f"{high_priority} require higher-priority review. "
            f"Final recruitment decisions should remain "
            f"with a qualified human reviewer."
        )

    # ------------------------------------------------------------------------
    # AVERAGE CONFIDENCE
    # ------------------------------------------------------------------------

    @staticmethod
    def _average_confidence(
        recommendations: List[Recommendation],
    ) -> float:

        if not recommendations:
            return 0.0

        return clamp(
            sum(
                recommendation.confidence
                for recommendation in recommendations
            )
            / len(recommendations)
        )

    # ------------------------------------------------------------------------
    # NUMBER
    # ------------------------------------------------------------------------

    @staticmethod
    def _number(
        value: Any,
    ) -> Optional[float]:

        if value is None:
            return None

        try:
            return float(value)
        except (
            TypeError,
            ValueError,
        ):
            return None

    # ------------------------------------------------------------------------
    # SERIALIZATION
    # ------------------------------------------------------------------------

    @staticmethod
    def to_dict(
        result: RecommendationResult,
    ) -> Dict[str, Any]:

        return asdict(
            result
        )


# ============================================================================
# DEFAULT ENGINE
# ============================================================================


default_recommendation_engine = (
    RecommendationEngine()
)


# ============================================================================
# CONVENIENCE FUNCTIONS
# ============================================================================


def generate_recommendations(
    *,
    candidate: Optional[
        Dict[str, Any]
    ] = None,
    job: Optional[
        Dict[str, Any]
    ] = None,
    resume: Optional[
        Dict[str, Any]
    ] = None,
    interview: Optional[
        Dict[str, Any]
    ] = None,
    analytics: Optional[
        Dict[str, Any]
    ] = None,
) -> RecommendationResult:
    """
    Generate recommendations using the default engine.
    """

    return default_recommendation_engine.generate(
        candidate=candidate,
        job=job,
        resume=resume,
        interview=interview,
        analytics=analytics,
    )


def recommend_candidate(
    candidate: Dict[str, Any],
    job: Optional[Dict[str, Any]] = None,
) -> Recommendation:
    """
    Generate a candidate recommendation.
    """

    return default_recommendation_engine.recommend_candidate(
        candidate,
        job,
    )


def recommend_skill_gaps(
    candidate: Dict[str, Any],
    job: Dict[str, Any],
) -> List[Recommendation]:
    """
    Generate skill-gap recommendations.
    """

    return default_recommendation_engine.recommend_skill_gaps(
        candidate,
        job,
    )


def recommend_resume(
    resume: Dict[str, Any],
    job: Optional[Dict[str, Any]] = None,
) -> List[Recommendation]:
    """
    Generate resume recommendations.
    """

    return default_recommendation_engine.recommend_resume_improvements(
        resume,
        job,
    )


def recommend_interview(
    candidate: Dict[str, Any],
    job: Dict[str, Any],
) -> Recommendation:
    """
    Generate interview recommendations.
    """

    return default_recommendation_engine.recommend_interview(
        candidate,
        job,
    )